def lorem_text():
  return"""
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac tortor eu enim ultricies lobortis eu at massa. Nulla tempor nulla sed fermentum posuere. Ut vel libero pulvinar, maximus eros ut, convallis orci. Nulla id tincidunt velit. Pellentesque lorem est, commodo ut velit sed, fringilla vulputate lacus. Integer vitae aliquam mauris, luctus venenatis lacus. Nam cursus quis odio ac imperdiet. In consectetur fringilla lorem, sed laoreet urna lobortis sed. Nam in mattis ipsum. Donec bibendum purus et condimentum cursus. Nam lectus enim, ullamcorper non erat quis, rhoncus sollicitudin metus. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Praesent eget turpis id tortor faucibus lobortis in ut elit. Nullam laoreet erat nulla, ut ornare erat placerat eu. Suspendisse potenti. In fermentum elit vel urna imperdiet, non convallis augue feugiat. Suspendisse ultrices eros id commodo volutpat. Phasellus aliquet arcu odio, vel dignissim nisi malesuada et. Duis volutpat suscipit tincidunt. Donec sollicitudin magna turpis, quis ultricies nisl auctor sit amet. Vivamus faucibus sit amet dolor vitae maximus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla id diam nunc. Aliquam non feugiat massa. Aenean fringilla maximus iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed elementum, nibh nec placerat vulputate, mauris elit mattis est, vel placerat enim lorem vel ex.

Phasellus eu sem eget purus mattis suscipit. Mauris congue dolor in egestas efficitur. Pellentesque mollis pulvinar orci. Cras id fermentum nulla, ut consequat turpis. Curabitur a est luctus, euismod nulla et, pellentesque nibh. Aliquam luctus leo in enim dictum cursus. Pellentesque tempus mollis elementum. Nam tempor fringilla neque, in tristique nibh consequat ut. Sed nec auctor purus. Pellentesque quis tincidunt nibh. Nunc ullamcorper metus vel euismod faucibus.

Suspendisse molestie aliquam accumsan. In nulla erat, feugiat nec interdum vel, malesuada id tellus. Quisque vitae porttitor sem, nec pharetra tortor. Ut blandit semper tortor, et efficitur est commodo nec. Donec tempus metus eu laoreet tincidunt. Etiam eu arcu elementum diam suscipit dignissim id ac risus. Quisque porttitor erat nec justo molestie, vel fermentum leo maximus. Mauris molestie mollis mollis. Nulla facilisi. Fusce ultrices tellus turpis, sit amet porta odio pellentesque vel. Nullam nec magna justo. Nullam tristique quam quis rutrum dictum. Etiam in ligula augue. Duis tempus sapien vitae laoreet rutrum.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec convallis lorem ac lorem bibendum pulvinar. Phasellus tempor mattis congue. Proin mollis tincidunt odio, eu gravida nisi tincidunt mattis. Nam vulputate felis eu sem vulputate, eu eleifend lorem semper. Integer ultrices nisl odio, non lobortis ligula condimentum ut. Aenean iaculis risus enim, eget consectetur lectus tincidunt sed. Fusce magna risus, facilisis et nunc id, mattis auctor nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse in cursus purus, quis lacinia lectus. Morbi eu tincidunt arcu. Mauris porttitor auctor massa. Donec pharetra maximus nisl vitae luctus. 
"""